# Generated by Django 5.1.3 on 2024-11-24 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('body_part', models.CharField(max_length=100)),
                ('equipment', models.CharField(blank=True, max_length=100, null=True)),
                ('gif_url', models.TextField(blank=True, null=True)),
                ('target', models.CharField(max_length=100)),
                ('secondary_muscles', models.TextField(blank=True, null=True)),
                ('instructions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserWorkout',
            fields=[
                ('workout_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_entries', to='workouts.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='workouts.userworkout')),
            ],
        ),
    ]
