# Generated by Django 5.1.3 on 2024-11-24 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('gym_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.TextField()),
                ('type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrowdData',
            fields=[
                ('crowd_id', models.AutoField(primary_key=True, serialize=False)),
                ('occupancy', models.FloatField()),
                ('last_updated', models.DateTimeField()),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crowd_data', to='gyms.gym')),
            ],
        ),
    ]
