# Generated by Django 5.1.3 on 2024-11-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowddata',
            name='percentage_full',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crowddata',
            name='occupancy',
            field=models.IntegerField(),
        ),
    ]
